
name: bitmagnet
services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    volumes:
      - /DATA/AppData/$AppID/config:/root/.config/bitmagnet
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "3334:3334/tcp"
      - "3334:3334/udp"
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      # disable the next line to run without DHT crawler
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    volumes:
      - /DATA/AppData/$AppID/postgres:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432" Expose this port if you'd like to dig around in the database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s



x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Main service for this application
  main: bitmagnet
  # Detailed description for the application
  description:
    en_us: |
      A self-hosted BitTorrent indexer, DHT crawler, content classifier and torrent search engine with web UI, GraphQL API and Servarr stack integration..
      - A DHT crawler and protocol implementation.
      - A torrent search engine. 

  developer: Bitmagnet.io
  
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitmagnet.png
  # Thumbnail image for the application (if any)
  # thumbnail: ""
  # Title for the application
  title:
    en_us: bitmagnet
  # Category under which the application falls
  category: Personal Apps
  port_map: '3333'
  tips:
    en_us: |
      "Edit the tsdproxy.yml inside the config folder."