name: opencloud
services:
  opencloud:
    image: opencloudeu/opencloud-rolling
    container_name: opencloud
    user: "568:568"
    volumes:
      - /DATA/AppData/$AppID/data/data:/var/lib/opencloud
      - /DATA/AppData/$AppID/data/config:/etc/opencloud
    ports:
      - 9200:9200
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init --insecure true || true; opencloud server"]
    environment:
      - OC_URL=https://IP-ADDRESS:9200 # https://IP-ADDRESS:9200 or https://cloud.yourdomain.com
      - IDM_CREATE_DEMO_USERS=false
    restart: unless-stopped
  #############################################
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Host awesome karaoke parties where everyone can easily find and queue songs from their phone's browser. The player is also fully browser-based with support for MP3+G, MP4 videos and WebGL visualizations. The server is self-hosted and runs on nearly everything.
      
      **Features:**
      - ⌨️ Keyboard shortcuts for quick file selection
      - 🖱️ Drag and drop support
      - 🔍 Powerful search by name, full text, OCR, file type, date, or tag
      - 🔄 Reliable, fault-tolerant file synchronization
      - 🔗 Flexible sharing options
      - 🌐 Share files with public links
      - 🗂️ Workspaces: Dedicated project folders designed to simplify team collaboration
      - 🛠️ Integrations with tools like Markdown Editor (ToastUI) and Web Office (Collabora)
      - 🕒 File history to track changes and restore previous versions
      - 📱 Multi-device sync with offline access across all your devices

      **Learn More:**
      - [Developer's Site](https://github.com/opencloud-eu)

    developer: "Opencloud-eu"
  
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-cloud-dark.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-cloud-dark.png
  title:
    en_us: Opencloud
  category: Personal Apps
  port_map: '9200'
  tagline:
    en_us: Fast, simple, and clean user interface!
  #####
  