#####
name: opencloud
services:
  app:
    image: opencloudeu/opencloud-rolling
    user: "568:568"
    volumes:
      - /DATA/AppData/$AppID/data/data:/var/lib/opencloud
      - /DATA/AppData/$AppID/data/config:/etc/opencloud
    restart: unless-stopped
    ports:
      - 9200:9200
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init --insecure true || true; opencloud server"]
    environment:
      - OC_URL=https://IP-ADDRESS:9200 # https://IP-ADDRESS:9200 or https://cloud.yourdomain.com
      - IDM_CREATE_DEMO_USERS=false
#
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Nextcloud alternative.
      **Features:**
      - Easy setup. You can even import from existing crontab.
      - Safe adding, deleting or pausing jobs. Easy to maintain hundreds of jobs.
      - Backup your crontabs.
      - Export crontab and deploy on other machines without much hassle.
      - Error log support.
      - Mailing and hooks support.
      
      - ⌨️ Keyboard shortcuts for quick file selection
      - 🖱️ Drag and drop support
      - 🔍 Powerful search by name, full text, OCR, file type, date, or tag
      - 🔄 Reliable, fault-tolerant file synchronization
      - 🔗 Flexible sharing options
      - 🌐 Share files with public links
      - 🗂️ Workspaces: Dedicated project folders designed to simplify team collaboration
      - 🛠️ Integrations with tools like Markdown Editor (ToastUI) and Web Office (Collabora)
      - 🕒 File history to track changes and restore previous versions
      - 📱 Multi-device sync with offline access across all your devices

      **Learn More:**
      - [Developer's Site](https://github.com/opencloud-eu/opencloud)
    developer: "Opencloud-eu"
  
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-cloud-dark.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-cloud-dark.png
  title:
    en_us: Openclouod
  category: Personal Apps
  port_map: '9200'
  tagline:
    en_us: Rsync between your servers!
  