name: crontab-ui
services:
  app:
    image: snoopcatt/asustor-crontabui
    restart: unless-stopped
    ports:
      - 8765:8000
    volumes:
      - /DATA/AppData/$AppID/crontabscripts:/etc/crontabscripts:rw      # This is where the scripts will be located
      - /DATA/Downloads:/data/personal:ro                            # Persistent log storage
      - /DATA/AppData/$AppID/.ssh:/root/.ssh:ro                   # Optional: mount SSH keys for rsync over SSH
    networks: {}
#
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: |
      Crontab Web GUI with Rsync for Backing up between different devices.
      
      - Easy setup. You can even import from existing crontab.
      - Safe adding, deleting or pausing jobs. Easy to maintain hundreds of jobs.
      - Backup your crontabs.
      - Export crontab and deploy on other machines without much hassle.
      - Error log support.
      - Mailing and hooks support.

      **Learn More:**
      - [Developer's Site](https://lifepluslinux.blogspot.com/2015/06/crontab-ui-easy-and-safe-way-to-manage.html)

    developer: "alseambusher"
  
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cron-master.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cron-master.png
  title:
    en_us: CrontabUI
  category: Personal Apps
  port_map: '8765'
  tagline:
    en_us: Rsync between your servers!