name: qbittorrentcustom
services:
  app:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/Downloads:/downloads #optional
    ports:
      - 28080:8080
      - 26881:6881
      - 26881:6881/udp
    restart: unless-stopped  

######################
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: The Qbittorrent project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library.
  tagline:
    en_us: The Qbittorrent project aims to provide an open-source software alternative to µTorrent. QBittorrent is based on the Qt toolkit and libtorrent-rasterbar library.
  developer: LinuxServer.io
  author: snoopcatt
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/qbittorrent.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/qbittorrent.png
  title:
    en_us: Qbittorrent
  category: Personal Only
  port_map: '8080'

---
