name: gluetun
services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN # This allows the container to perform network operations.
    devices:
      - /dev/net/tun:/dev/net/tun # Map the TUN device, required for VPNs.
    # Expose and map specific ports from the container to the host.
    ports:
      - 8888:8888/tcp # HTTP proxy port mapping.
      - 8388:8388/tcp # Shadowsocks TCP port mapping.
      - 8388:8388/udp # Shadowsocks UDP port mapping.
      - 8080:8080 # qbittorrent port
      - 6881:6881 # qbittorrent port
      - 6881:6881/udp # qbittorrent port
      - 7000:3000      # Firefox Port
      - 7001:3001      # Firefox Port
      - 9696:9696      # Prowlarr Port
      
    # Map volumes from the host to the container.
    volumes:
      - /DATA/AppData/$AppID/data:/gluetun # Map the data directory.

    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP="PUBLIC IP OF YOUR VPS"
      - WIREGUARD_ENDPOINT_PORT="WIREGUARD CUSTOM PORT"
      - WIREGUARD_PUBLIC_KEY=""
      - WIREGUARD_PRIVATE_KEY=""
      - WIREGUARD_PRESHARED_KEY=""
      - WIREGUARD_ADDRESSES=10.8.0.5/24
      - TZ=Asia/Singapore
########################################### QBITTORRENT STACK ##########################################################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - TORRENTING_PORT=6881
    volumes:
      - /DATA/AppData/$AppID/qbittorrentconfig:/config
      - /DATA/Downloads:/downloads #optional
    restart: unless-stopped
######################################################### FIREFOX STACK ###############################################################################
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /DATA/AppData/$AppID/firefox:/config
    shm_size: "1gb"
    restart: unless-stopped
    network_mode: "service:gluetun"       # ADD THIS LINE EVERYTIME YOU ADD A NEW STACK TO GLUETUN TO ROUTE TRAFFIC THROUGH GLUETUN
######################################################### PROWLARR STACK ###############################################################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - /DATA/AppData/$AppID/prowlarr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"       # ADD THIS LINE EVERYTIME YOU ADD A NEW STACK TO GLUETUN TO ROUTE TRAFFIC THROUGH GLUETUN

#######################################################################################################################################################

x-casaos:
  architectures:
    - amd64
  # Main service for this application
  main: gluetun
  description:
    en_us: |
      Lightweight swiss-knife-like VPN client to multiple VPN service providers
      **Features:**
      - Based on Alpine 3.22 for a small Docker image of 41.1MB
      - Supports Wireguard.

  tagline:
    en_us: Gluetun
  developer: "Quentin McGaw"
  author: snoopcatt
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/gluetun.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/gluetun.png
#######################################################################################################################################################

  # Installation tips
  tips:
    before_install:
      en_us: |
        **Notes**
        - Qbittorrent: http://localhost:8080 and the username and password can be found in the logs.
        - See devbeloper's site for info [Gluetun Docs](https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md)
        - Firefox: https://localhost:7001
        - Prowlarr: http://localhost:9696

  title:
    en_us: Gluetun Plus
  category: Personal Apps
  port_map: ""
#######################################################################################################################################################
