name: backrest
services:
  app:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data:/data
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/cache:/cache
      - /DATA/AppData/$AppID/tmp:/tmp
      - /DATA/AppData/$AppID/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - /DATA/AppData/$AppID/userdata:/userdata  # Mount local paths to backup
      - /DATA/AppData/$AppID/sourcedata:/sourcedata # DATA to backup
      - /DATA/AppData/$AppID/repo:/repos     # Mount local repos (optional for remote storage)

    environment:
      - TZ=Asia/Singapore
    ports:
      - "9898:9898"
    

# CASAOS ENVIRONMENT VARIABLES AND METADATA     


x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Backrest is a web-accessible backup solution built on top of restic. Backrest provides a WebUI which wraps the restic CLI and makes it easy to create repos, browse snapshots, and restore files. Additionally, Backrest can run in the background and take an opinionated approach to scheduling snapshots and orchestrating repo health operations. 
  developer: Gareth
  
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/backrest.png
  thumbnail: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/backrest.png
  
  title:
    en_us: Backrest
  category: Personal Apps
  port_map: '9898'