name: drawio
services:
  app:
    image: jgraph/drawio
    restart: unless-stopped
    ports:
      - 5180:8080
      - 5183:8443

# CASAOS ENVIRONMENT VARIABLES AND METADATA     

x-casaos:
  architectures:
    - amd64
  main: drawio
  description:
    en_us: draw.io is a whiteboarding / diagramming software application..
  developer: "JGraph"
  
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/draw-io.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_us: draw.io
  # Category under which the application falls
  category: Personal Apps
  tagline:
    en_us: Diagram your homelab!